services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: planify_local
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - planify_db:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build:
      context: ./apps/web
    env_file:
      - ./apps/web/.env
    environment:
      DATABASE_URL: postgresql://postgres:planify_local@db:5432/postgres
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: planify_minio
      S3_SECRET: planify_minio_secret
      S3_BUCKET: planify
      S3_REGION: us-east-1
      S3_PUBLIC_URL: http://localhost:9000
    depends_on:
      - db
      - redis
      - minio
    ports:
      - "3000:3000"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: planify_minio
      MINIO_ROOT_PASSWORD: planify_minio_secret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - planify_minio:/data

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 2;
      mc alias set planify http://minio:9000 planify_minio planify_minio_secret;
      mc mb -p planify/planify || true;
      mc anonymous set download planify/planify || true;
      exit 0;
      "

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./ops/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - planify_prometheus:/prometheus
    ports:
      - "9090:9090"

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yml"]
    volumes:
      - ./ops/tempo.yml:/etc/tempo.yml:ro
      - planify_tempo:/tmp/tempo
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
      - tempo
    ports:
      - "3001:3000"
    volumes:
      - planify_grafana:/var/lib/grafana

volumes:
  planify_db:
  planify_minio:
  planify_prometheus:
  planify_tempo:
  planify_grafana:
